// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XPTOMVC.Data;

namespace XPTOMVC.Migrations
{
    [DbContext(typeof(XPTOMVCContext))]
    [Migration("20240815172432_4")]
    partial class _4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("XPTOMVC.Models.Servico", b =>
                {
                    b.Property<string>("Titulo")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.HasKey("Titulo");

                    b.ToTable("Servico");
                });
#pragma warning restore 612, 618
        }
    }
}
