// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XPTOMVC.Data;

namespace XPTOMVC.Migrations
{
    [DbContext(typeof(XPTOMVCContext))]
    [Migration("20240815161854_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("XPTOMVC.Models.Cliente", b =>
                {
                    b.Property<string>("CNPJ")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("CNPJ");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("XPTOMVC.Models.OS", b =>
                {
                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClienteCNPJ");

                    b.Property<DateTime>("DataExecucao");

                    b.Property<string>("ProvedorServicoCPF");

                    b.Property<string>("ServicoTitulo");

                    b.Property<double>("ValorServico");

                    b.HasKey("Numero");

                    b.HasIndex("ClienteCNPJ");

                    b.HasIndex("ProvedorServicoCPF");

                    b.HasIndex("ServicoTitulo");

                    b.ToTable("OS");
                });

            modelBuilder.Entity("XPTOMVC.Models.ProvedorServico", b =>
                {
                    b.Property<string>("CPF")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("CPF");

                    b.ToTable("ProvedorServico");
                });

            modelBuilder.Entity("XPTOMVC.Models.Servico", b =>
                {
                    b.Property<string>("Titulo")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Titulo");

                    b.ToTable("Servico");
                });

            modelBuilder.Entity("XPTOMVC.Models.OS", b =>
                {
                    b.HasOne("XPTOMVC.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteCNPJ");

                    b.HasOne("XPTOMVC.Models.ProvedorServico", "ProvedorServico")
                        .WithMany()
                        .HasForeignKey("ProvedorServicoCPF");

                    b.HasOne("XPTOMVC.Models.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoTitulo");
                });
#pragma warning restore 612, 618
        }
    }
}
